#!/usr/bin/python
import sys, re

#Required parts
requiredRegex = "#\\w.+$|#NOCLICKUP"
requiredLength = 15


#Get the commit file
commitMessageFile = open(sys.argv[1]) #The first argument is the file
commitMessage = commitMessageFile.read().strip()

if len(commitMessage) < requiredLength:
    print("Commit message is less than the required 15 characters.")
    sys.exit(1)

if re.search(requiredRegex, commitMessage) is None:
    print("A Clickup issue must be linked")
    sys.exit(1)

print("Commit message is validated")
sys.exit(0)